[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/pins"
restartPolicyType = "ON_FAILURE"
