[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev --no-audit --no-fund && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/auth/session"
restartPolicyType = "ON_FAILURE"
